### ISSUE TITLE
more fast to calculate large scales eQTL

### ISSUE THREAD

**Issue by XXyangLiu** [alanocallaghan/baseqtl#1]
Thank you for developing this fantastic R package. I am using it to study the eQTL effects in a large number of samples. In my usage, I have designed a loop to individually analyze each gene using BaseQTL calculations. I have designed a loop to individually analyze each gene using BaseQTL calculations. It can produce the results I need, but sometimes it gets killed by the system due to excessive memory usage, and some genes take too long to compute. Therefore, I’m eager to know if there is a more efficient and memory-saving way to do this?”
Thank you！

**Comment by alanocallaghan** [comment]
Hi, sorry this is just a mirror, the actual repo is https://gitlab.com/evigorito/baseqtl/, I'd suggest opening an issue there or asking Elena Vigorito directly
